### ISSUE TITLE
EC612 overspeed issue

### ISSUE THREAD

**Issue by progettista6** [Elite-Robots/ROS#3]
Hello,

in my laptop I cloned this repository. I'm working with Ubuntu 18.04 LTS and ROS Melodic. 
I tried to command an EC612 robot with the following firmware and software versions:

Controller software V3.3.2.2022061
Servo software V11.39

I launched the EC612 controllers and the related elite_moveit.launch file, and everything works well: in fact Rviz panel showed the correct configuration for the robot.
When I tried to command a movement, both in cartesian coordinates and in joint coordinates, the robot moves very sharply and this caused an overspeed error.
I tried to reduce velocity and acceleration limits in the related joint_limits.yaml as follows:

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 3.0 #2.094395102393195
    has_acceleration_limits: true
    max_acceleration: 1.0 #0
  joint2:
    has_velocity_limits: true
    max_velocity: 3.0 #2.094395102393195
    has_acceleration_limits: true
    max_acceleration: 1.0 #0
  joint3:
    has_velocity_limits: true
    max_velocity: 3.0 #2.617993877991494
    has_acceleration_limits: true
    max_acceleration: 1.0 #0
  joint4:
    has_velocity_limits: true
    max_velocity: 3.0 #3.665191429188092
    has_acceleration_limits: true
    max_acceleration: 1.0 #0
  joint5:
    has_velocity_limits: true
    max_velocity: 3.0 #3.665191429188092
    has_acceleration_limits: true
    max_acceleration: 1.0 #0
  joint6:
    has_velocity_limits: true
    max_velocity: 3.0 #3.665191429188092
    has_acceleration_limits: true
    max_acceleration: 1.0 #0

Also with these limits, the problem remains unsolved.
Could you help me to solve this issue?

Thank you

**Comment by Elite-Robots** [comment]
Does this problem occur the moment the robot starts up? And we recommend that the ros package be used on ubuntu2004.
