### ISSUE TITLE
What is the difference between elirobot and elirobots

### ISSUE THREAD

**Issue by elevenjiang1** [Elite-Robots/ROS#9]
The README.md written in ```https://github.com/Elite-Robots/ROS``` is pip3 install elirobots
However the doc in ```https://www.yuque.com/haoqiguaio/queyunote/dbxtl8?#IY7B1``` is pip install elirobot
So what is the difference?

Meanwhile, I am curious about is it possible to control multi EC66 robots with ROS? or only can control by elirobot package

**Comment by JunJie-zhang-o** [comment]
elirobots is the python package for elite ec robot.
you need to use pip install elirobots or pip3 install elirobots. the yuque link will remove from document in next  version.

 you can use roslaunch to start multi rosnodes to control different robot in ros.
 
 elirobots package is a simple implementation of sdk. You can write codes in different languages to control the robot according to the sdk manual. Of course, you can also control multiple robots at the same time.
 
 Here is the link to our forum.[elibot forum](https://bbs.elibot.cn/)

**Comment by JunJie-zhang-o** [comment]
![image](https://user-images.githubusercontent.com/78187633/201306806-acdb3705-28bb-4e81-8fad-ac8de6013040.png)
this is English section
